"""Add cart models (Fase 3)

Revision ID: b8541dfccbfb
Revises: 1bde40595f80
Create Date: 2026-02-10 00:35:14.644876+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8541dfccbfb'
down_revision = '1bde40595f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('storefront_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('cart_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR anonymous_id IS NOT NULL', name='ck_cart_user_or_anonymous'),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storefront_id', 'anonymous_id', name='uq_cart_storefront_anonymous')
    )
    op.create_index(op.f('ix_carts_storefront_id'), 'carts', ['storefront_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'FACEBOOK', 'APPLE', 'GITHUB', name='oauth_provider', native_enum=False), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=2000), nullable=True),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_provider_provider_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_oauth_connections_email'), 'oauth_connections', ['email'], unique=False)
    op.create_index(op.f('ix_oauth_connections_provider'), 'oauth_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connections_provider_id'), 'oauth_connections', ['provider_id'], unique=False)
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('storefront_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATING_STOCK', 'RESERVED', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='order_status', native_enum=False), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ABS(total_amount - (subtotal + shipping_amount + tax_amount)) < 0.01', name='ck_order_total_calculation'),
    sa.CheckConstraint('shipping_amount >= 0', name='ck_order_shipping_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_order_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_order_tax_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_order_total_non_negative'),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_storefront_id'), 'orders', ['storefront_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'VERIFY_EMAIL', 'VERIFY_PHONE', 'RESET_PASSWORD', name='otp_purpose', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('storefront_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storefront_id'], ['storefronts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'code', 'purpose', name='uq_email_code_purpose'),
    sa.UniqueConstraint('phone', 'code', 'purpose', name='uq_phone_code_purpose')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_index('ix_otp_codes_email_expires', 'otp_codes', ['email', 'expires_at'], unique=False)
    op.create_index('ix_otp_codes_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_index('ix_otp_codes_phone_expires', 'otp_codes', ['phone', 'expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_storefront_id'), 'otp_codes', ['storefront_id'], unique=False)
    op.create_index(op.f('ix_otp_codes_used'), 'otp_codes', ['used'], unique=False)
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_addition', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_item_positive_quantity'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', 'variant_id', name='uq_cart_item_cart_product_variant')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('variant_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("product_name != ''", name='ck_order_item_product_name_not_empty'),
    sa.CheckConstraint("product_sku != ''", name='ck_order_item_product_sku_not_empty'),
    sa.CheckConstraint('ABS(total_price - (unit_price * quantity)) < 0.01', name='ck_order_item_total_calculation'),
    sa.CheckConstraint('product_id IS NOT NULL OR variant_id IS NOT NULL', name='ck_order_item_product_or_variant'),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='ck_order_item_total_price_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_sku'), 'order_items', ['product_sku'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'VALIDATING_STOCK', 'RESERVED', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='order_status', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('CREATED', 'VALIDATING_STOCK', 'RESERVED', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='order_status', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('changed_by_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_changed_by_type'), 'order_status_history', ['changed_by_type'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_history_reason'), 'order_status_history', ['reason'], unique=False)
    op.create_index(op.f('ix_order_status_history_to_status'), 'order_status_history', ['to_status'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'CONFIRMED', name='stock_reservation_status', native_enum=False), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status != 'confirmed' OR confirmed_at IS NOT NULL) AND (status = 'confirmed' OR confirmed_at IS NULL)", name='ck_stock_reservation_confirmed_timestamp'),
    sa.CheckConstraint("(status != 'released' OR released_at IS NOT NULL) AND (status = 'released' OR released_at IS NULL)", name='ck_stock_reservation_released_timestamp'),
    sa.CheckConstraint('expires_at > created_at', name='ck_stock_reservation_expires_after_created'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_reservation_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reservations_expires_at'), 'stock_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_stock_reservations_inventory_id'), 'stock_reservations', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_order_id'), 'stock_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_status'), 'stock_reservations', ['status'], unique=False)
    # Add new columns as nullable first
    op.add_column('users', sa.Column('user_type', sa.Enum('ADMIN', 'CUSTOMER', name='user_type', native_enum=False), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE users SET user_type = 'ADMIN' WHERE user_type IS NULL")
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE users SET phone_verified = false WHERE phone_verified IS NULL")
    
    # Now alter columns to NOT NULL
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_unique_constraint('uq_storefront_email', 'users', ['storefront_id', 'email'])
    op.create_unique_constraint('uq_storefront_phone', 'users', ['storefront_id', 'phone'])
    op.drop_constraint(op.f('users_storefront_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'storefronts', ['storefront_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_storefront_id_fkey'), 'users', 'storefronts', ['storefront_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_storefront_phone', 'users', type_='unique')
    op.drop_constraint('uq_storefront_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'user_type')
    op.drop_index(op.f('ix_stock_reservations_status'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_order_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_inventory_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_expires_at'), table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index(op.f('ix_order_status_history_to_status'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_reason'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_changed_by_type'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_sku'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_used'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_storefront_id'), table_name='otp_codes')
    op.drop_index('ix_otp_codes_phone_expires', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index('ix_otp_codes_expires_at', table_name='otp_codes')
    op.drop_index('ix_otp_codes_email_expires', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_storefront_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_provider_id'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_provider'), table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_email'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_storefront_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
